name: curific CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: node-version:[14.x,15.x,16.x,17.x,18.x]

    steps:
      - uses: action/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v2
        with: node-version:${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
